### ISSUE TITLE
How to performed unbuffered operation

### ISSUE THREAD

**Issue by dvaldivia** [jonhoo/streamunordered#1]
Hi, I'm wondering how to wrap a `StreamUnordered` in a buffered manner, similar to `.buffer_unordered` (which underneath uses `FuturesUnordered`)

**Comment by jonhoo** [comment]
Hi! There isn't currently such a feature, but it shouldn't be too tricky to add. I'd be happy to review a PR!

**Comment by dvaldivia** [comment]
What would be a good strategy?

I'm taking `futures_unordered` as a starting point, which seems like a good candidate.

```
pub fn futures_unordered<I>(futures: I) -> FuturesUnordered<<I::Item as IntoFuture>::Future>
    where I: IntoIterator,
        I::Item: IntoFuture
{
    let mut set = FuturesUnordered::new();

    for future in futures {
        set.push(future.into_future());
    }

    return set
}
```

However, since `IntoStream` is not a trait I cannot simply have it cast the `I::Item` as a `IntoStream` so I'm getting stuck there, seems like it cannot be an auxiliary function can it

**Comment by dvaldivia** [comment]
Ideally maybe 
```
pub fn stream_unordered<I>(streams: I) -> StreamUnordered<<I::Item as IntoStream>::Stream>
    where I: IntoIterator,
          I::Item: IntoStream
{
    let mut set = StreamUnordered::new();

    for strm in streams {
        set.push(strm.into_stream());
    }

    return set
}
```
but the fact that `IntoStream` is not a trait, gets in the way, I'm fairly new to rust so I don't know a way around this limitation, but with some guidance I'll gladly look into it

**Comment by jonhoo** [comment]
Sadly I'm pretty busy these days, so probably won't have time to implement this feature myself, but if you want to take a stab at it, the basic idea would be to add something like:

```rust
struct BufferedStreamUnordered<S> where S: Stream {
    streams: StreamUnordered<S>,
    pending: FuturesUnordered<S::Item>,
    limit: usize,
}
```

and then

```rust
impl<S> Stream for BufferedStreamUnordered<S>
where
  S: Stream,
  S::Item: Future {
    fn poll(&mut self) -> ... {
        while self.pending.len() < self.limit {
            match self.stream.poll()? {
                Async::Ready(Some(f)) => self.pending.push(f),
                Async::NotReady | Async::Ready(None) => break,
            }
        }
        
        self.pending.poll()
    }
}
```

If you do try to implement it, I'd be happy to review a PR! If you could also add some documentation and some tests, that'd be great (copying from `futures` should be fine!).
